@host = http://localhost:3001

### Register User
POST {{host}}/auth/register
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@gmail.com",
  "password": "password",
  "role": "admin"
}

### Register User
POST {{host}}/auth/register
Content-Type: application/json

{
  "name": "user",
  "email": "user@gmail.com",
  "password": "password",
  "role": "customer"
}

### Login User
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "password"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoyLCJyb2xlIjoiYWRtaW4iLCJzbHVnIjoiYWRtaW4iLCJpYXQiOjE3NzU3MTg5ODF9.zCBdU4sYlOi0UUqpbglQmG_tfiwblZDm7txQ7ieFwXI

POST {{host}}/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "stickeeer",
  "description": "category description"
}

### Get All Categories
GET {{host}}/category
Content-Type: application/json
Authorization: Bearer {{token}}

### Get One Category
GET {{host}}/category/2
Content-Type: application/json
Authorization: Bearer {{token}}

### Get One Category
PUT {{host}}/category/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "smartphone stickers",
  "description": "category description"
}


### Get One Category
DELETE  {{host}}/category/3
Content-Type: application/json
Authorization: Bearer {{token}}

### Change Status
PUT  {{host}}/category/2/status
Content-Type: application/json
Authorization: Bearer {{token}}