import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "sonner";
import { TitleChange } from "@/utils/title";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <Suspense fallback={<Loading />}>
        <AuthProvider>
          <TitleChange />
          <body>
            {children}
            <Toaster closeButton position="top-center" />
          </body>
        </AuthProvider>
      </Suspense>
    </html>
  );
}
