export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const jwtConstants = 'secret';

export const CATEGORIES_REPOSITORY = 'CATEGORIES_REPOSITORY';

export const PRODUCTS_REPOSITORY = 'PRODUCTS_REPOSITORY';
export const PRODUCT_HAS_CATEGORY_REPOSITORY =
  'PRODUCT_HAS_CATEGORY_REPOSITORY';
export const PRODUCT_HAS_MEDIA_REPOSITORY = 'PRODUCT_HAS_MEDIA_REPOSITORY';

export const ORDER_REPOSITORY = 'ORDER_REPOSITORY';

export const PAYMENT_REPOSITORY = 'PAYMENT_REPOSITORY';

export const CART_REPOSITORY = 'CART_REPOSITORY';
